<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
        'template_map' => array(
            'ckeditor' => __DIR__ . '/../view/editor/index.phtml',
        ),
    ),

    'controllers' => array(
        'invokables'=> array(
            'Ckeditor\Controller\Index' => 'Ckeditor\Controller\IndexController'
        )
    ),

    'service_manager' => array(),

    'router' => array(
        'routes' => array(
            'ckeditor' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/ckeditor[/:action][/:id]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id' => '[0-9]*',
                    ),
                    'defaults' => array(
                        '__NAMESPACE__' => 'Ckeditor\Controller',
                        'controller' => 'Index',
                        'action' => 'index',
                    ),

                )
            )
        ),
        'may_terminate' => true,
        'child_routes' => []
    )
);